alert("Sizda hozir  random sonlar chiqishi boshlaydi !")
let RandomSon =  Math.floor(Math.random() * 100)
alert("Random orqali chiqqan son " + (RandomSon))
alert("Biz random sonni 2ga bo'lib ko'paytirmoqchimiz")
alert("Random orqali chiqqan son " + (RandomSon) + "\n" + "Biz uni 2ga ko'paytirib "  + (RandomSon * 2) + "\n" + "Biz uni 2ga bo'lganimizda " + (RandomSon / 2) + "\n" + "Va bu sonni 3ga bo'lganimizda qoldiq :" + (RandomSon % 3)) 